# Generated by Django 4.2.7 on 2024-02-29 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_alter_customuser_birth_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='birth_year',
        ),
    ]
