# Generated by Django 4.2.7 on 2024-02-29 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_customuser_age_customuser_birth_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
