# Generated by Django 5.0.2 on 2024-03-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(help_text='Upload PDF or JPEG files only.', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='visibility',
            field=models.BooleanField(default=True, help_text='Set visibility'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='year_published',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
