# Generated by Django 4.2.7 on 2024-03-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_alter_uploadedfile_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='john', max_length=30, unique=True),
        ),
    ]
