# Generated by Django 4.2.7 on 2024-03-01 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
