# Generated by Django 4.2.7 on 2024-03-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_somemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='cover_photo',
            field=models.ImageField(blank=True, help_text='Upload cover photo', null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(help_text='Upload PDF ', upload_to='uploads/'),
        ),
        migrations.DeleteModel(
            name='SomeModel',
        ),
    ]
